# Generated by Django 3.0.5 on 2020-05-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('training_name', models.CharField(max_length=120)),
                ('certificate_validity', models.CharField(max_length=120)),
                ('date', models.CharField(max_length=120, null=True)),
                ('place', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='idcard',
            name='certificate_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='circle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='customer_account_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='employment_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
