# Generated by Django 3.0.5 on 2020-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200512_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_validity',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='place',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='training_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='certificate_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
