# Generated by Django 3.0.5 on 2020-05-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
