# Generated by Django 3.0.5 on 2020-05-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_report_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
