# Generated by Django 3.0.5 on 2020-05-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200516_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='q1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='q10',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='q11',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='q2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='q3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='q4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='q5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='q6',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='q7',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='q8',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='q9',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True),
        ),
    ]
