# Generated by Django 3.0.5 on 2020-05-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200516_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_examination',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='registration_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
