# Generated by Django 2.2.4 on 2020-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200531_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
